name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 18
    - run: npm install
    - if: matrix.os == 'windows-latest'
      run: |
        npm run make-win
        ls ./out/make/zip
        mkdir -p ./download && cp ./out/make/zip/x64/* ./download
    
    - if: matrix.os == 'ubuntu-latest'
      run: |
        npm run make-linux
        mkdir -p ./download && cp ./out/make/deb/x64/* ./download
      
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: downloads