name: Build/release

on: push

jobs:
  release:
    runs-on: deployment

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
        run: npm install
        run: npm run make-win 
        run: ls
      
      # - name: Step 3 - Use the Upload Artifact GitHub Action
      #   uses: actions/upload-artifact@v2
      #   with: 
      #     name: assets-for-download
      #     path: downloads